modLoader="javafml" 
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]] 
modId="featherduskmod" 
version="1.0" 
displayName="Featherdusk's Magic Mod" 
credits="Thanks for this mod" 
authors="Featherdusk"
description='''

Welcome to Featherdusk's Magic Mod! All new items can be found in the
custom creative tab on the second page!




'''

